---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foo--bar
---
apiVersion: v1
kind: Secret
metadata:
  namespace: shoot--foo--bar
  name: core-gcp
type: Opaque
data:
# serviceaccount.json: base64(serviceaccount-json)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  namespace: shoot--foo--bar
  name: shoot--foo--bar
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    spec:
      cloud:
        gcp:
          networks:
            pods: 10.243.128.0/17
            services: 10.243.0.0/17
    status:
      lastOperation:
        state: Succeeded

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  namespace: shoot--foo--bar
  name: gcp-infra
spec:
  type: gcp
  region: europe-west1
  secretRef:
    namespace: shoot--foo--bar
    name: core-gcp
  providerConfig:
    apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      worker: 10.242.0.0/19
      # internal: 10.243.0.0/19

