// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/gardener-extensions/pkg/controller/controlplane/genericactuator (interfaces: ValuesProvider,ChartRendererFactory)

// Package genericactuator is a generated GoMock package.
package genericactuator

import (
	context "context"
	controller "github.com/gardener/gardener-extensions/pkg/controller"
	v1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	chartrenderer "github.com/gardener/gardener/pkg/chartrenderer"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockValuesProvider is a mock of ValuesProvider interface
type MockValuesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockValuesProviderMockRecorder
}

// MockValuesProviderMockRecorder is the mock recorder for MockValuesProvider
type MockValuesProviderMockRecorder struct {
	mock *MockValuesProvider
}

// NewMockValuesProvider creates a new mock instance
func NewMockValuesProvider(ctrl *gomock.Controller) *MockValuesProvider {
	mock := &MockValuesProvider{ctrl: ctrl}
	mock.recorder = &MockValuesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValuesProvider) EXPECT() *MockValuesProviderMockRecorder {
	return m.recorder
}

// GetConfigChartValues mocks base method
func (m *MockValuesProvider) GetConfigChartValues(arg0 context.Context, arg1 *v1alpha1.ControlPlane, arg2 *controller.Cluster) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigChartValues", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigChartValues indicates an expected call of GetConfigChartValues
func (mr *MockValuesProviderMockRecorder) GetConfigChartValues(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigChartValues", reflect.TypeOf((*MockValuesProvider)(nil).GetConfigChartValues), arg0, arg1, arg2)
}

// GetControlPlaneChartValues mocks base method
func (m *MockValuesProvider) GetControlPlaneChartValues(arg0 context.Context, arg1 *v1alpha1.ControlPlane, arg2 *controller.Cluster, arg3 map[string]string, arg4 bool) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControlPlaneChartValues", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControlPlaneChartValues indicates an expected call of GetControlPlaneChartValues
func (mr *MockValuesProviderMockRecorder) GetControlPlaneChartValues(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControlPlaneChartValues", reflect.TypeOf((*MockValuesProvider)(nil).GetControlPlaneChartValues), arg0, arg1, arg2, arg3, arg4)
}

// GetControlPlaneShootChartValues mocks base method
func (m *MockValuesProvider) GetControlPlaneShootChartValues(arg0 context.Context, arg1 *v1alpha1.ControlPlane, arg2 *controller.Cluster) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControlPlaneShootChartValues", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControlPlaneShootChartValues indicates an expected call of GetControlPlaneShootChartValues
func (mr *MockValuesProviderMockRecorder) GetControlPlaneShootChartValues(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControlPlaneShootChartValues", reflect.TypeOf((*MockValuesProvider)(nil).GetControlPlaneShootChartValues), arg0, arg1, arg2)
}

// MockChartRendererFactory is a mock of ChartRendererFactory interface
type MockChartRendererFactory struct {
	ctrl     *gomock.Controller
	recorder *MockChartRendererFactoryMockRecorder
}

// MockChartRendererFactoryMockRecorder is the mock recorder for MockChartRendererFactory
type MockChartRendererFactoryMockRecorder struct {
	mock *MockChartRendererFactory
}

// NewMockChartRendererFactory creates a new mock instance
func NewMockChartRendererFactory(ctrl *gomock.Controller) *MockChartRendererFactory {
	mock := &MockChartRendererFactory{ctrl: ctrl}
	mock.recorder = &MockChartRendererFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChartRendererFactory) EXPECT() *MockChartRendererFactoryMockRecorder {
	return m.recorder
}

// NewChartRendererForShoot mocks base method
func (m *MockChartRendererFactory) NewChartRendererForShoot(arg0 string) (chartrenderer.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChartRendererForShoot", arg0)
	ret0, _ := ret[0].(chartrenderer.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChartRendererForShoot indicates an expected call of NewChartRendererForShoot
func (mr *MockChartRendererFactoryMockRecorder) NewChartRendererForShoot(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChartRendererForShoot", reflect.TypeOf((*MockChartRendererFactory)(nil).NewChartRendererForShoot), arg0)
}
