---
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: garden.sapcloud.io:psp:calico
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: garden.sapcloud.io:psp:kube-system:calico
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system
