apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-config
  namespace: {{ .Release.Namespace }}
data:
  cloudprovider.conf: |
    [Global]
    auth-url="{{ .Values.authUrl }}"
    domain-name="{{ .Values.domainName }}"
    tenant-name="{{ .Values.tenantName }}"
    username="{{ .Values.username }}"
    password="{{ .Values.password }}"
    [LoadBalancer]
    lb-version=v2
    lb-provider="{{ .Values.lbProvider }}"
    floating-network-id="{{ .Values.floatingNetworkID }}"
    {{- if .Values.floatingSubnetID }}
    floating-subnet-id="{{ .Values.floatingSubnetID }}"
    {{- end }}
    {{- if .Values.subnetID }}
    subnet-id="{{ .Values.subnetID }}"
    {{- end }}
    create-monitor=true
    monitor-delay=60s
    monitor-timeout=30s
    monitor-max-retries=5
    {{- if and (semverCompare ">= 1.10.1" .Values.kubernetesVersion) (semverCompare "< 1.10.3" .Values.kubernetesVersion) }}
    [Metadata]
    {{- if (ne .Values.dhcpDomain "") }}
    dhcp-domain="{{ .Values.dhcpDomain }}"
    {{- end }}
    {{- if (ne .Values.requestTimeout "") }}
    request-timeout={{ .Values.requestTimeout }}
    {{- end }}
    {{- end }}
    {{- range $i, $class := .Values.floatingClasses }}
    [LoadBalancerClass {{ $class.name | quote }}]
    {{- if $class.floatingNetworkID }}
    floating-network-id="{{ $class.floatingNetworkID }}"
    {{- end }}
    {{- if $class.floatingSubnetID }}
    floating-subnet-id="{{ $class.floatingSubnetID }}"
    {{- end }}
    {{- if $class.subnetID }}
    subnet-id="{{ $class.subnetID }}"
    {{- end }}
    {{- end }}