{{- if .Values.config.typha.enabled }}
---
# This manifest creates a Pod Disruption Budget for Typha to allow K8s Cluster Autoscaler to evict
 apiVersion: {{ include "poddisruptionbudgetversion" . }}
 kind: PodDisruptionBudget
 metadata:
   name: calico-typha
   namespace: kube-system
   labels:
     k8s-app: calico-typha
 spec:
   maxUnavailable: 1
   selector:
     matchLabels:
       k8s-app: calico-typha
{{- end }}
