{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.calico-typha
spec:
  volumes:
  - secret
  hostNetwork: true
  hostPorts:
  - min: 5473
    max: 5473
  - min: 9098
    max: 9098
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
{{- end }}
