{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: typha-cpha
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "get"]
{{- end }}
