{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: calico-typha-horizontal-autoscaler
  namespace: kube-system
  labels:
    origin: gardener
    k8s-app: calico-typha-autoscaler
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      k8s-app: calico-typha-autoscaler
  template:
    metadata:
      annotations:
        checksum/configmap-calico-typha-horizontal-autoscaler: {{ include (print $.Template.BasePath "/typha-cpha/configmap-typha-horizontal-autoscaling.yaml") . | sha256sum }}
      labels:
        origin: gardener
        k8s-app: calico-typha-autoscaler
    spec:
      priorityClassName: system-cluster-critical
      securityContext:
        supplementalGroups: [ 65534 ]
        fsGroup: 65534
        runAsUser: 65534
      containers:
        - image: {{ index .Values.images "typha-cpa" }}
          name: autoscaler
          command:
            - /cluster-proportional-autoscaler
            - --namespace=kube-system
            - --configmap=calico-typha-horizontal-autoscaler
            - --target=deployment/calico-typha-deploy
            - --logtostderr=true
            - --v=2
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 10m
              memory: 50Mi
      serviceAccountName: typha-cpha
{{- end }}
