#!/usr/bin/env bash

set -e

descriptor_out_file="${COMPONENT_DESCRIPTOR_PATH}"
dir="$(dirname "$0")"

for images_yaml_path in "$dir/../controllers/"*"/charts/images.yaml"; do
  images="$(yaml2json < $images_yaml_path)"

  echo "enriching creating component descriptor from ${BASE_DEFINITION_PATH}"
  controller_dir="$(basename "$(dirname "$(dirname "${images_yaml_path}")")")"

  eval "$(jq -r ".images |
    map(if (.name == \"hyperkube\") then
      \"--generic-dependencies '{\\\"name\\\": \\\"\" + .name + \"\\\", \\\"version\\\": \\\"\" + .tag + \"\\\"}'\"
    elif (.repository | startswith(\"eu.gcr.io/gardener-project/gardener\")) then
      \"--component-dependencies '{\\\"name\\\": \\\"\" + .sourceRepository + \"\\\", \\\"version\\\": \\\"\" + .tag + \"\\\"}'\"
    else
      \"--container-image-dependencies '{\\\"name\\\": \\\"${controller_dir}-\" + .name + \"\\\", \\\"image_reference\\\": \\\"\" + .repository + \":\" + .tag + \"\\\", \\\"version\\\": \\\"\" + .tag + \"\\\"}'\"
    end) |
    \"${ADD_DEPENDENCIES_CMD} \\\\\n\" +
    join(\" \\\\\n\")" <<< "$images")"
done

cp "${BASE_DEFINITION_PATH}" "${descriptor_out_file}"
