#!/usr/bin/env sh
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

apk update
apk add --no-cache \
    ca-certificates \
    make \
    bash \
    go \
    git \
    musl-dev \
    curl \
    openssl \
    tar \
    gcc \
    sed

if [ -z "$REPO_DIR" ]; then
    export REPO_DIR="$(readlink -f "$(dirname "$0")"/..)"
else
    export REPO_DIR="$(readlink -f "$REPO_DIR")"
fi

GOLANG_VERSION="$(sed -rn 's/FROM golang:([^ ]+).*/\1/p' < "$REPO_DIR/Dockerfile")"

if [ -z "$EFFECTIVE_VERSION" ]; then
    version="$(cat "$REPO_DIR/VERSION")"
    if [ -z "$version" ]; then
        echo "Version not found"
        exit 1
    fi
else
    version="${EFFECTIVE_VERSION}"
fi

export \
    GOROOT="$(go env GOROOT)" \
    GOOS="$(go env GOOS)" \
    GOARCH="$(go env GOARCH)" \
    GOHOSTOS="$(go env GOHOSTOS)" \
    GOHOSTARCH="$(go env GOHOSTARCH)" \
    GOPATH=/go \
    GOBIN="$GOPATH/bin" \
    PATH="$GOBIN:$PATH"

wget -O - "https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz" | tar zx -C /usr/local

"$REPO_DIR"/hack/install-requirements.sh

make -C "$REPO_DIR" generate

