{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    garden.sapcloud.io/purpose: machineclass
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  authURL: {{ $machineClass.secret.authURL | b64enc }}
  insecure: dHJ1ZQ== # true
  {{- if $machineClass.secret.domainName }}
  domainName: {{ $machineClass.secret.domainName | b64enc }}
  {{- end }}
  {{- if $machineClass.secret.domainID }}
  domainID: {{ $machineClass.secret.domainID | b64enc }}
  {{- end }}
  {{- if $machineClass.secret.tenantName }}
  tenantName: {{ $machineClass.secret.tenantName | b64enc }}
  {{- end }}
  {{- if $machineClass.secret.tenantID }}
  tenantID: {{ $machineClass.secret.tenantID | b64enc }}
  {{- end }}
  {{- if $machineClass.secret.userDomainName }}
  userDomainName: {{ $machineClass.secret.userDomainName }}
  {{- end }}
  {{- if $machineClass.secret.userDomainID }}
  userDomainID: {{ $machineClass.secret.userDomainID }}
  {{- end }}
  username: {{ $machineClass.secret.username | b64enc }}
  password: {{ $machineClass.secret.password | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: OpenStackMachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  region: {{ $machineClass.region }}
  availabilityZone: {{ $machineClass.availabilityZone }}
  flavorName: {{ $machineClass.machineType }}
  keyName: {{ $machineClass.keyName }}
  imageName: {{ $machineClass.imageName }}
  networkID: {{ $machineClass.networkID }}
  podNetworkCidr: {{ $machineClass.podNetworkCidr }}
  securityGroups:
{{ toYaml $machineClass.securityGroups | indent 2 }}
  secretRef:
    name: {{ $machineClass.name }}
    namespace: {{ $.Release.Namespace }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
{{- end }}
