---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: garden
type: Opaque
data:
# accessKeyID: base64(access-key-id)
# accessKeySecret: base64(access-key-secret)

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: cloud--ali--fg2d6
spec:
  type: alicloud
  region: eu-west-1
  secretRef:
    name: backupprovider
    namespace: garden
