---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--alicloud
---
apiVersion: v1
kind: Secret
metadata:
  namespace: shoot--foobar--alicloud
  name: cloudprovider
type: Opaque
data:
# accessKeyID: base64(accessKeyID)
# accessKeySecret: base64(accessKeySecret)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--alicloud
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
    spec:
      alicloud:
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      networking:
        pods: 10.243.128.0/17
        services: 10.243.0.0/17
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  namespace: shoot--foobar--alicloud
  name: alicloud-infra
spec:
  type: alicloud
  region: cn-beijing
  secretRef:
    namespace: shoot--foobar--alicloud
    name: cloudprovider
# sshPublicKey: base64(sshPublicKey)
  providerConfig:
    apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      vpc: # specify either 'id' or 'cidr'
      # id: my-vpc
        cidr: 10.250.0.0/16
      zones:
      - name: cn-beijing-f
        workers: 10.250.1.0/24
