---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-shoot-cert-service
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-cert-service
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - gardener-extension-shoot-cert-service
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - dns.gardener.cloud
  resources:
  - dnsentries
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
- apiGroups:
  - "cert.gardener.cloud"
  resources:
  - issuers
  - issuers/status
  verbs:
  - get
  - update
  - patch
