// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	service "github.com/gardener/gardener-extensions/controllers/extension-shoot-cert-service/pkg/apis/service"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CertConfig)(nil), (*service.CertConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertConfig_To_service_CertConfig(a.(*CertConfig), b.(*service.CertConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*service.CertConfig)(nil), (*CertConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_service_CertConfig_To_v1alpha1_CertConfig(a.(*service.CertConfig), b.(*CertConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IssuerConfig)(nil), (*service.IssuerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IssuerConfig_To_service_IssuerConfig(a.(*IssuerConfig), b.(*service.IssuerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*service.IssuerConfig)(nil), (*IssuerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_service_IssuerConfig_To_v1alpha1_IssuerConfig(a.(*service.IssuerConfig), b.(*IssuerConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CertConfig_To_service_CertConfig(in *CertConfig, out *service.CertConfig, s conversion.Scope) error {
	out.Issuers = *(*[]service.IssuerConfig)(unsafe.Pointer(&in.Issuers))
	return nil
}

// Convert_v1alpha1_CertConfig_To_service_CertConfig is an autogenerated conversion function.
func Convert_v1alpha1_CertConfig_To_service_CertConfig(in *CertConfig, out *service.CertConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CertConfig_To_service_CertConfig(in, out, s)
}

func autoConvert_service_CertConfig_To_v1alpha1_CertConfig(in *service.CertConfig, out *CertConfig, s conversion.Scope) error {
	out.Issuers = *(*[]IssuerConfig)(unsafe.Pointer(&in.Issuers))
	return nil
}

// Convert_service_CertConfig_To_v1alpha1_CertConfig is an autogenerated conversion function.
func Convert_service_CertConfig_To_v1alpha1_CertConfig(in *service.CertConfig, out *CertConfig, s conversion.Scope) error {
	return autoConvert_service_CertConfig_To_v1alpha1_CertConfig(in, out, s)
}

func autoConvert_v1alpha1_IssuerConfig_To_service_IssuerConfig(in *IssuerConfig, out *service.IssuerConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Server = in.Server
	out.Email = in.Email
	return nil
}

// Convert_v1alpha1_IssuerConfig_To_service_IssuerConfig is an autogenerated conversion function.
func Convert_v1alpha1_IssuerConfig_To_service_IssuerConfig(in *IssuerConfig, out *service.IssuerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_IssuerConfig_To_service_IssuerConfig(in, out, s)
}

func autoConvert_service_IssuerConfig_To_v1alpha1_IssuerConfig(in *service.IssuerConfig, out *IssuerConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Server = in.Server
	out.Email = in.Email
	return nil
}

// Convert_service_IssuerConfig_To_v1alpha1_IssuerConfig is an autogenerated conversion function.
func Convert_service_IssuerConfig_To_v1alpha1_IssuerConfig(in *service.IssuerConfig, out *IssuerConfig, s conversion.Scope) error {
	return autoConvert_service_IssuerConfig_To_v1alpha1_IssuerConfig(in, out, s)
}
