#!/bin/bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

helm package "$(dirname $0)/../charts/gardener-extension-os-coreos" --destination "$(dirname $0)/.."
chart="$(cat $(dirname $0)/../gardener-extension-os-coreos-*.tgz | base64 | tr -d '\n')"
rm -f "$(dirname $0)/../gardener-extension-os-coreos-"*.tgz

cat <<EOF > "$(dirname $0)/../example/controllerregistration-os-coreos.yaml"
---
apiVersion: gardener.cloud/v1alpha1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  deployment:
    type: helm
    providerConfig:
      chart: $chart
      values:
        image:
          tag: $(cat VERSION)
EOF
