// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	vsphere "github.com/gardener/gardener-extensions/controllers/provider-vsphere/pkg/apis/vsphere"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*vsphere.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_vsphere_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*vsphere.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*vsphere.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*vsphere.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_vsphere_CloudProfileConfig(a.(*CloudProfileConfig), b.(*vsphere.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*vsphere.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Constraints)(nil), (*vsphere.Constraints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Constraints_To_vsphere_Constraints(a.(*Constraints), b.(*vsphere.Constraints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.Constraints)(nil), (*Constraints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_Constraints_To_v1alpha1_Constraints(a.(*vsphere.Constraints), b.(*Constraints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*vsphere.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_vsphere_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*vsphere.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*vsphere.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FailureDomainLabels)(nil), (*vsphere.FailureDomainLabels)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FailureDomainLabels_To_vsphere_FailureDomainLabels(a.(*FailureDomainLabels), b.(*vsphere.FailureDomainLabels), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.FailureDomainLabels)(nil), (*FailureDomainLabels)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_FailureDomainLabels_To_v1alpha1_FailureDomainLabels(a.(*vsphere.FailureDomainLabels), b.(*FailureDomainLabels), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*vsphere.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_vsphere_InfrastructureConfig(a.(*InfrastructureConfig), b.(*vsphere.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*vsphere.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*vsphere.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_vsphere_InfrastructureStatus(a.(*InfrastructureStatus), b.(*vsphere.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*vsphere.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancerClass)(nil), (*vsphere.LoadBalancerClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LoadBalancerClass_To_vsphere_LoadBalancerClass(a.(*LoadBalancerClass), b.(*vsphere.LoadBalancerClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.LoadBalancerClass)(nil), (*LoadBalancerClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_LoadBalancerClass_To_v1alpha1_LoadBalancerClass(a.(*vsphere.LoadBalancerClass), b.(*LoadBalancerClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancerConfig)(nil), (*vsphere.LoadBalancerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LoadBalancerConfig_To_vsphere_LoadBalancerConfig(a.(*LoadBalancerConfig), b.(*vsphere.LoadBalancerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.LoadBalancerConfig)(nil), (*LoadBalancerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_LoadBalancerConfig_To_v1alpha1_LoadBalancerConfig(a.(*vsphere.LoadBalancerConfig), b.(*LoadBalancerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*vsphere.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_vsphere_MachineImage(a.(*MachineImage), b.(*vsphere.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_MachineImage_To_v1alpha1_MachineImage(a.(*vsphere.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*vsphere.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_vsphere_MachineImageVersion(a.(*MachineImageVersion), b.(*vsphere.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*vsphere.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*vsphere.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_vsphere_MachineImages(a.(*MachineImages), b.(*vsphere.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_MachineImages_To_v1alpha1_MachineImages(a.(*vsphere.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Networks)(nil), (*vsphere.Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Networks_To_vsphere_Networks(a.(*Networks), b.(*vsphere.Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.Networks)(nil), (*Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_Networks_To_v1alpha1_Networks(a.(*vsphere.Networks), b.(*Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionSpec)(nil), (*vsphere.RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionSpec_To_vsphere_RegionSpec(a.(*RegionSpec), b.(*vsphere.RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.RegionSpec)(nil), (*RegionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_RegionSpec_To_v1alpha1_RegionSpec(a.(*vsphere.RegionSpec), b.(*RegionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VsphereConfig)(nil), (*vsphere.VsphereConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VsphereConfig_To_vsphere_VsphereConfig(a.(*VsphereConfig), b.(*vsphere.VsphereConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.VsphereConfig)(nil), (*VsphereConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_VsphereConfig_To_v1alpha1_VsphereConfig(a.(*vsphere.VsphereConfig), b.(*VsphereConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*vsphere.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_vsphere_WorkerStatus(a.(*WorkerStatus), b.(*vsphere.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*vsphere.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ZoneConfig)(nil), (*vsphere.ZoneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ZoneConfig_To_vsphere_ZoneConfig(a.(*ZoneConfig), b.(*vsphere.ZoneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.ZoneConfig)(nil), (*ZoneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_ZoneConfig_To_v1alpha1_ZoneConfig(a.(*vsphere.ZoneConfig), b.(*ZoneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ZoneSpec)(nil), (*vsphere.ZoneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ZoneSpec_To_vsphere_ZoneSpec(a.(*ZoneSpec), b.(*vsphere.ZoneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*vsphere.ZoneSpec)(nil), (*ZoneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_vsphere_ZoneSpec_To_v1alpha1_ZoneSpec(a.(*vsphere.ZoneSpec), b.(*ZoneSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_vsphere_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *vsphere.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_vsphere_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_vsphere_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *vsphere.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_vsphere_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_vsphere_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *vsphere.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_vsphere_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_vsphere_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *vsphere.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_vsphere_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_vsphere_CloudProfileConfig(in *CloudProfileConfig, out *vsphere.CloudProfileConfig, s conversion.Scope) error {
	out.NamePrefix = in.NamePrefix
	out.Folder = in.Folder
	out.Regions = *(*[]vsphere.RegionSpec)(unsafe.Pointer(&in.Regions))
	out.DefaultClassStoragePolicyName = in.DefaultClassStoragePolicyName
	out.FailureDomainLabels = (*vsphere.FailureDomainLabels)(unsafe.Pointer(in.FailureDomainLabels))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.MachineImages = *(*[]vsphere.MachineImages)(unsafe.Pointer(&in.MachineImages))
	if err := Convert_v1alpha1_Constraints_To_vsphere_Constraints(&in.Constraints, &out.Constraints, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_vsphere_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_vsphere_CloudProfileConfig(in *CloudProfileConfig, out *vsphere.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_vsphere_CloudProfileConfig(in, out, s)
}

func autoConvert_vsphere_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *vsphere.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.NamePrefix = in.NamePrefix
	out.Folder = in.Folder
	out.Regions = *(*[]RegionSpec)(unsafe.Pointer(&in.Regions))
	out.DefaultClassStoragePolicyName = in.DefaultClassStoragePolicyName
	out.FailureDomainLabels = (*FailureDomainLabels)(unsafe.Pointer(in.FailureDomainLabels))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	if err := Convert_vsphere_Constraints_To_v1alpha1_Constraints(&in.Constraints, &out.Constraints, s); err != nil {
		return err
	}
	return nil
}

// Convert_vsphere_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_vsphere_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *vsphere.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_vsphere_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_Constraints_To_vsphere_Constraints(in *Constraints, out *vsphere.Constraints, s conversion.Scope) error {
	if err := Convert_v1alpha1_LoadBalancerConfig_To_vsphere_LoadBalancerConfig(&in.LoadBalancerConfig, &out.LoadBalancerConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Constraints_To_vsphere_Constraints is an autogenerated conversion function.
func Convert_v1alpha1_Constraints_To_vsphere_Constraints(in *Constraints, out *vsphere.Constraints, s conversion.Scope) error {
	return autoConvert_v1alpha1_Constraints_To_vsphere_Constraints(in, out, s)
}

func autoConvert_vsphere_Constraints_To_v1alpha1_Constraints(in *vsphere.Constraints, out *Constraints, s conversion.Scope) error {
	if err := Convert_vsphere_LoadBalancerConfig_To_v1alpha1_LoadBalancerConfig(&in.LoadBalancerConfig, &out.LoadBalancerConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_vsphere_Constraints_To_v1alpha1_Constraints is an autogenerated conversion function.
func Convert_vsphere_Constraints_To_v1alpha1_Constraints(in *vsphere.Constraints, out *Constraints, s conversion.Scope) error {
	return autoConvert_vsphere_Constraints_To_v1alpha1_Constraints(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_vsphere_ControlPlaneConfig(in *ControlPlaneConfig, out *vsphere.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*vsphere.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.LoadBalancerClassNames = *(*[]string)(unsafe.Pointer(&in.LoadBalancerClassNames))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_vsphere_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_vsphere_ControlPlaneConfig(in *ControlPlaneConfig, out *vsphere.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_vsphere_ControlPlaneConfig(in, out, s)
}

func autoConvert_vsphere_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *vsphere.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.LoadBalancerClassNames = *(*[]string)(unsafe.Pointer(&in.LoadBalancerClassNames))
	return nil
}

// Convert_vsphere_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_vsphere_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *vsphere.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_vsphere_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_FailureDomainLabels_To_vsphere_FailureDomainLabels(in *FailureDomainLabels, out *vsphere.FailureDomainLabels, s conversion.Scope) error {
	out.Region = in.Region
	out.Zone = in.Zone
	return nil
}

// Convert_v1alpha1_FailureDomainLabels_To_vsphere_FailureDomainLabels is an autogenerated conversion function.
func Convert_v1alpha1_FailureDomainLabels_To_vsphere_FailureDomainLabels(in *FailureDomainLabels, out *vsphere.FailureDomainLabels, s conversion.Scope) error {
	return autoConvert_v1alpha1_FailureDomainLabels_To_vsphere_FailureDomainLabels(in, out, s)
}

func autoConvert_vsphere_FailureDomainLabels_To_v1alpha1_FailureDomainLabels(in *vsphere.FailureDomainLabels, out *FailureDomainLabels, s conversion.Scope) error {
	out.Region = in.Region
	out.Zone = in.Zone
	return nil
}

// Convert_vsphere_FailureDomainLabels_To_v1alpha1_FailureDomainLabels is an autogenerated conversion function.
func Convert_vsphere_FailureDomainLabels_To_v1alpha1_FailureDomainLabels(in *vsphere.FailureDomainLabels, out *FailureDomainLabels, s conversion.Scope) error {
	return autoConvert_vsphere_FailureDomainLabels_To_v1alpha1_FailureDomainLabels(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_vsphere_InfrastructureConfig(in *InfrastructureConfig, out *vsphere.InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_Networks_To_vsphere_Networks(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_vsphere_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_vsphere_InfrastructureConfig(in *InfrastructureConfig, out *vsphere.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_vsphere_InfrastructureConfig(in, out, s)
}

func autoConvert_vsphere_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *vsphere.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_vsphere_Networks_To_v1alpha1_Networks(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_vsphere_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_vsphere_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *vsphere.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_vsphere_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_vsphere_InfrastructureStatus(in *InfrastructureStatus, out *vsphere.InfrastructureStatus, s conversion.Scope) error {
	out.Network = in.Network
	out.LogicalSwitchId = in.LogicalSwitchId
	out.LogicalRouterId = in.LogicalRouterId
	if err := Convert_v1alpha1_VsphereConfig_To_vsphere_VsphereConfig(&in.VsphereConfig, &out.VsphereConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_vsphere_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_vsphere_InfrastructureStatus(in *InfrastructureStatus, out *vsphere.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_vsphere_InfrastructureStatus(in, out, s)
}

func autoConvert_vsphere_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *vsphere.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	out.Network = in.Network
	out.LogicalSwitchId = in.LogicalSwitchId
	out.LogicalRouterId = in.LogicalRouterId
	if err := Convert_vsphere_VsphereConfig_To_v1alpha1_VsphereConfig(&in.VsphereConfig, &out.VsphereConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_vsphere_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_vsphere_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *vsphere.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_vsphere_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_LoadBalancerClass_To_vsphere_LoadBalancerClass(in *LoadBalancerClass, out *vsphere.LoadBalancerClass, s conversion.Scope) error {
	out.Name = in.Name
	out.IPPoolName = in.IPPoolName
	return nil
}

// Convert_v1alpha1_LoadBalancerClass_To_vsphere_LoadBalancerClass is an autogenerated conversion function.
func Convert_v1alpha1_LoadBalancerClass_To_vsphere_LoadBalancerClass(in *LoadBalancerClass, out *vsphere.LoadBalancerClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_LoadBalancerClass_To_vsphere_LoadBalancerClass(in, out, s)
}

func autoConvert_vsphere_LoadBalancerClass_To_v1alpha1_LoadBalancerClass(in *vsphere.LoadBalancerClass, out *LoadBalancerClass, s conversion.Scope) error {
	out.Name = in.Name
	out.IPPoolName = in.IPPoolName
	return nil
}

// Convert_vsphere_LoadBalancerClass_To_v1alpha1_LoadBalancerClass is an autogenerated conversion function.
func Convert_vsphere_LoadBalancerClass_To_v1alpha1_LoadBalancerClass(in *vsphere.LoadBalancerClass, out *LoadBalancerClass, s conversion.Scope) error {
	return autoConvert_vsphere_LoadBalancerClass_To_v1alpha1_LoadBalancerClass(in, out, s)
}

func autoConvert_v1alpha1_LoadBalancerConfig_To_vsphere_LoadBalancerConfig(in *LoadBalancerConfig, out *vsphere.LoadBalancerConfig, s conversion.Scope) error {
	out.Size = in.Size
	out.Classes = *(*[]vsphere.LoadBalancerClass)(unsafe.Pointer(&in.Classes))
	return nil
}

// Convert_v1alpha1_LoadBalancerConfig_To_vsphere_LoadBalancerConfig is an autogenerated conversion function.
func Convert_v1alpha1_LoadBalancerConfig_To_vsphere_LoadBalancerConfig(in *LoadBalancerConfig, out *vsphere.LoadBalancerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_LoadBalancerConfig_To_vsphere_LoadBalancerConfig(in, out, s)
}

func autoConvert_vsphere_LoadBalancerConfig_To_v1alpha1_LoadBalancerConfig(in *vsphere.LoadBalancerConfig, out *LoadBalancerConfig, s conversion.Scope) error {
	out.Size = in.Size
	out.Classes = *(*[]LoadBalancerClass)(unsafe.Pointer(&in.Classes))
	return nil
}

// Convert_vsphere_LoadBalancerConfig_To_v1alpha1_LoadBalancerConfig is an autogenerated conversion function.
func Convert_vsphere_LoadBalancerConfig_To_v1alpha1_LoadBalancerConfig(in *vsphere.LoadBalancerConfig, out *LoadBalancerConfig, s conversion.Scope) error {
	return autoConvert_vsphere_LoadBalancerConfig_To_v1alpha1_LoadBalancerConfig(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_vsphere_MachineImage(in *MachineImage, out *vsphere.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Path = in.Path
	out.GuestID = in.GuestID
	return nil
}

// Convert_v1alpha1_MachineImage_To_vsphere_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_vsphere_MachineImage(in *MachineImage, out *vsphere.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_vsphere_MachineImage(in, out, s)
}

func autoConvert_vsphere_MachineImage_To_v1alpha1_MachineImage(in *vsphere.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Path = in.Path
	out.GuestID = in.GuestID
	return nil
}

// Convert_vsphere_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_vsphere_MachineImage_To_v1alpha1_MachineImage(in *vsphere.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_vsphere_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_vsphere_MachineImageVersion(in *MachineImageVersion, out *vsphere.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Path = in.Path
	out.GuestID = in.GuestID
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_vsphere_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_vsphere_MachineImageVersion(in *MachineImageVersion, out *vsphere.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_vsphere_MachineImageVersion(in, out, s)
}

func autoConvert_vsphere_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *vsphere.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Path = in.Path
	out.GuestID = in.GuestID
	return nil
}

// Convert_vsphere_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_vsphere_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *vsphere.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_vsphere_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_vsphere_MachineImages(in *MachineImages, out *vsphere.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]vsphere.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_vsphere_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_vsphere_MachineImages(in *MachineImages, out *vsphere.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_vsphere_MachineImages(in, out, s)
}

func autoConvert_vsphere_MachineImages_To_v1alpha1_MachineImages(in *vsphere.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_vsphere_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_vsphere_MachineImages_To_v1alpha1_MachineImages(in *vsphere.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_vsphere_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_Networks_To_vsphere_Networks(in *Networks, out *vsphere.Networks, s conversion.Scope) error {
	out.Worker = in.Worker
	return nil
}

// Convert_v1alpha1_Networks_To_vsphere_Networks is an autogenerated conversion function.
func Convert_v1alpha1_Networks_To_vsphere_Networks(in *Networks, out *vsphere.Networks, s conversion.Scope) error {
	return autoConvert_v1alpha1_Networks_To_vsphere_Networks(in, out, s)
}

func autoConvert_vsphere_Networks_To_v1alpha1_Networks(in *vsphere.Networks, out *Networks, s conversion.Scope) error {
	out.Worker = in.Worker
	return nil
}

// Convert_vsphere_Networks_To_v1alpha1_Networks is an autogenerated conversion function.
func Convert_vsphere_Networks_To_v1alpha1_Networks(in *vsphere.Networks, out *Networks, s conversion.Scope) error {
	return autoConvert_vsphere_Networks_To_v1alpha1_Networks(in, out, s)
}

func autoConvert_v1alpha1_RegionSpec_To_vsphere_RegionSpec(in *RegionSpec, out *vsphere.RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.VsphereHost = in.VsphereHost
	out.VsphereInsecureSSL = in.VsphereInsecureSSL
	out.NSXTHost = in.NSXTHost
	out.NSXTInsecureSSL = in.NSXTInsecureSSL
	out.TransportZone = in.TransportZone
	out.LogicalTier0Router = in.LogicalTier0Router
	out.EdgeCluster = in.EdgeCluster
	out.SNATIPPool = in.SNATIPPool
	out.Datacenter = in.Datacenter
	out.Datastore = in.Datastore
	out.DatastoreCluster = in.DatastoreCluster
	out.Zones = *(*[]vsphere.ZoneSpec)(unsafe.Pointer(&in.Zones))
	out.CaFile = in.CaFile
	out.Thumbprint = in.Thumbprint
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.MachineImages = *(*[]vsphere.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_RegionSpec_To_vsphere_RegionSpec is an autogenerated conversion function.
func Convert_v1alpha1_RegionSpec_To_vsphere_RegionSpec(in *RegionSpec, out *vsphere.RegionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionSpec_To_vsphere_RegionSpec(in, out, s)
}

func autoConvert_vsphere_RegionSpec_To_v1alpha1_RegionSpec(in *vsphere.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.VsphereHost = in.VsphereHost
	out.VsphereInsecureSSL = in.VsphereInsecureSSL
	out.NSXTHost = in.NSXTHost
	out.NSXTInsecureSSL = in.NSXTInsecureSSL
	out.TransportZone = in.TransportZone
	out.LogicalTier0Router = in.LogicalTier0Router
	out.EdgeCluster = in.EdgeCluster
	out.SNATIPPool = in.SNATIPPool
	out.Datacenter = in.Datacenter
	out.Datastore = in.Datastore
	out.DatastoreCluster = in.DatastoreCluster
	out.Zones = *(*[]ZoneSpec)(unsafe.Pointer(&in.Zones))
	out.CaFile = in.CaFile
	out.Thumbprint = in.Thumbprint
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_vsphere_RegionSpec_To_v1alpha1_RegionSpec is an autogenerated conversion function.
func Convert_vsphere_RegionSpec_To_v1alpha1_RegionSpec(in *vsphere.RegionSpec, out *RegionSpec, s conversion.Scope) error {
	return autoConvert_vsphere_RegionSpec_To_v1alpha1_RegionSpec(in, out, s)
}

func autoConvert_v1alpha1_VsphereConfig_To_vsphere_VsphereConfig(in *VsphereConfig, out *vsphere.VsphereConfig, s conversion.Scope) error {
	out.Folder = in.Folder
	out.Region = in.Region
	out.ZoneConfigs = *(*map[string]vsphere.ZoneConfig)(unsafe.Pointer(&in.ZoneConfigs))
	return nil
}

// Convert_v1alpha1_VsphereConfig_To_vsphere_VsphereConfig is an autogenerated conversion function.
func Convert_v1alpha1_VsphereConfig_To_vsphere_VsphereConfig(in *VsphereConfig, out *vsphere.VsphereConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_VsphereConfig_To_vsphere_VsphereConfig(in, out, s)
}

func autoConvert_vsphere_VsphereConfig_To_v1alpha1_VsphereConfig(in *vsphere.VsphereConfig, out *VsphereConfig, s conversion.Scope) error {
	out.Folder = in.Folder
	out.Region = in.Region
	out.ZoneConfigs = *(*map[string]ZoneConfig)(unsafe.Pointer(&in.ZoneConfigs))
	return nil
}

// Convert_vsphere_VsphereConfig_To_v1alpha1_VsphereConfig is an autogenerated conversion function.
func Convert_vsphere_VsphereConfig_To_v1alpha1_VsphereConfig(in *vsphere.VsphereConfig, out *VsphereConfig, s conversion.Scope) error {
	return autoConvert_vsphere_VsphereConfig_To_v1alpha1_VsphereConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_vsphere_WorkerStatus(in *WorkerStatus, out *vsphere.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]vsphere.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_vsphere_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_vsphere_WorkerStatus(in *WorkerStatus, out *vsphere.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_vsphere_WorkerStatus(in, out, s)
}

func autoConvert_vsphere_WorkerStatus_To_v1alpha1_WorkerStatus(in *vsphere.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_vsphere_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_vsphere_WorkerStatus_To_v1alpha1_WorkerStatus(in *vsphere.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_vsphere_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}

func autoConvert_v1alpha1_ZoneConfig_To_vsphere_ZoneConfig(in *ZoneConfig, out *vsphere.ZoneConfig, s conversion.Scope) error {
	out.Datacenter = in.Datacenter
	out.ComputeCluster = in.ComputeCluster
	out.ResourcePool = in.ResourcePool
	out.HostSystem = in.HostSystem
	out.Datastore = in.Datastore
	out.DatastoreCluster = in.DatastoreCluster
	return nil
}

// Convert_v1alpha1_ZoneConfig_To_vsphere_ZoneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ZoneConfig_To_vsphere_ZoneConfig(in *ZoneConfig, out *vsphere.ZoneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ZoneConfig_To_vsphere_ZoneConfig(in, out, s)
}

func autoConvert_vsphere_ZoneConfig_To_v1alpha1_ZoneConfig(in *vsphere.ZoneConfig, out *ZoneConfig, s conversion.Scope) error {
	out.Datacenter = in.Datacenter
	out.ComputeCluster = in.ComputeCluster
	out.ResourcePool = in.ResourcePool
	out.HostSystem = in.HostSystem
	out.Datastore = in.Datastore
	out.DatastoreCluster = in.DatastoreCluster
	return nil
}

// Convert_vsphere_ZoneConfig_To_v1alpha1_ZoneConfig is an autogenerated conversion function.
func Convert_vsphere_ZoneConfig_To_v1alpha1_ZoneConfig(in *vsphere.ZoneConfig, out *ZoneConfig, s conversion.Scope) error {
	return autoConvert_vsphere_ZoneConfig_To_v1alpha1_ZoneConfig(in, out, s)
}

func autoConvert_v1alpha1_ZoneSpec_To_vsphere_ZoneSpec(in *ZoneSpec, out *vsphere.ZoneSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Datacenter = in.Datacenter
	out.ComputeCluster = in.ComputeCluster
	out.ResourcePool = in.ResourcePool
	out.HostSystem = in.HostSystem
	out.Datastore = in.Datastore
	out.DatastoreCluster = in.DatastoreCluster
	return nil
}

// Convert_v1alpha1_ZoneSpec_To_vsphere_ZoneSpec is an autogenerated conversion function.
func Convert_v1alpha1_ZoneSpec_To_vsphere_ZoneSpec(in *ZoneSpec, out *vsphere.ZoneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ZoneSpec_To_vsphere_ZoneSpec(in, out, s)
}

func autoConvert_vsphere_ZoneSpec_To_v1alpha1_ZoneSpec(in *vsphere.ZoneSpec, out *ZoneSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Datacenter = in.Datacenter
	out.ComputeCluster = in.ComputeCluster
	out.ResourcePool = in.ResourcePool
	out.HostSystem = in.HostSystem
	out.Datastore = in.Datastore
	out.DatastoreCluster = in.DatastoreCluster
	return nil
}

// Convert_vsphere_ZoneSpec_To_v1alpha1_ZoneSpec is an autogenerated conversion function.
func Convert_vsphere_ZoneSpec_To_v1alpha1_ZoneSpec(in *vsphere.ZoneSpec, out *ZoneSpec, s conversion.Scope) error {
	return autoConvert_vsphere_ZoneSpec_To_v1alpha1_ZoneSpec(in, out, s)
}
