---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--packet
type: Opaque
data:
  apiToken: ZGF0YQo=
  projectID: ZGF0YQo=
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--packet
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
    spec:
      providerConfig:
        apiVersion: packet.provider.extensions.gardener.cloud/v1alpha1
        kind: CloudProfileConfig
        machineImages:
        - name: coreos
          versions:
          - version: 2023.5.0
            id: packetimageid
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      kubernetes:
        version: 1.13.4
    status:
      lastOperation:
        state: Succeeded
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# needed infrastructure does probably not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foobar--packet
  annotations:
    gardener.cloud/operation: reconcile
spec:
  type: packet
  region: ewr1
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--packet
  infrastructureProviderStatus:
    apiVersion: packet.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
  pools:
  - name: cpu-worker
    machineType: c1.small
    machineImage:
      name: coreos
      version: 2023.5.0
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
  # labels:
  #   key: value
  # annotations:
  #   key: value
  # taints: # See also https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # - key: foo
  #   value: bar
  #   effect: NoSchedule
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    zones:
    - ewr1
