---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foo--bar
type: Opaque
data:
# apiToken: base64(api-token)
# projectID: base64(project-id)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foo--bar
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    status:
      lastOperation:
        state: Succeeded
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# needed infrastructure does probably not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foo--bar
spec:
  type: packet
  region: EWR1
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar
  infrastructureProviderStatus:
    apiVersion: packet.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
  pools:
  - name: cpu-worker
    machineType: c1.small
    machineImage:
      name: coreos
      version: 2023.5.0
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    zones:
    - EWR1
