machineClasses:
- name: class-1
  region: europe-1
  availabilityZone: europe-1a
  machineType: medium_2_4
  keyName: my-ssh-key
  imageName: coreos-v1.0
  networkID: 426428cd-5e88-4005-9fad-9555d4dfd0fb
  podNetworkCidr: 100.96.0.0/11
  securityGroups:
  - my-security-group
  tags:
    kubernetes.io/cluster/shoot-crazy-botany: "1"
    kubernetes.io/role/node: "1"
  secret:
    authURL: ABCD
    # at least one of domainName or domainID has to be provided
    # domainName: ABCD
    # domainID: abc-123
    # at least one of tenantName or tenantID has to be provided
    # tenantName: abc
    # tenantID: abc-123
    # userDomainName: ABCD # optional
    # userDomainID: abc-123 # optional
    username: abc
    password: abc
    cloudConfig: abc
