apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-{{ .Values.serviceName }}
      containers:
      - name: gardener-extension-{{ .Values.serviceName }}
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - {{ .Values.serviceName }}-extension-controller-manager
        - --max-concurrent-reconciles={{ .Values.controllers.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --garden-id={{ .Values.gardener.garden.identity }}
        - --seed-id={{ .Values.gardener.seed.identity }}
        - --dns-class={{ .Values.dnsClass }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        {{- end }}
