apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-certificate-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-certificate-service
    helm.sh/chart: gardener-extension-certificate-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-certificate-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret-certificate-service-config: {{ include "certconfig" . | sha256sum }}
      labels:
        app.kubernetes.io/name: gardener-extension-certificate-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-certificate-service
      containers:
      - name: gardener-extension-certificate-service
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - certificate-service-controller-manager
        - --max-concurrent-reconciles={{ .Values.controllers.concurrentSyncs }}
        - --config=/etc/certificate-service/config/config.yaml
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        {{- end }}
        volumeMounts:
          - name: certificate-service-config
            mountPath: /etc/certificate-service/config
            readOnly: true
      volumes:
      - name: certificate-service-config
        secret:
          secretName: extension-certificate-service
