# Default values for cert-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

images:
  cert-broker: eu.gcr.io/gardener-project/gardener/cert-broker:0.2.0

certbroker:
  replicaWorkers: 4
  cleanupWorkers: 1
  controlClusterSecret:
  targetClusterSecret: "target-cluster"

certmanager:
  clusterissuer: "gardener-issuer"
  acmeChallengeType: "dns01"
  updateIngress: "true"
  leaderElection: "true"
  dns:
  - domain: "example.com"
    provider: "route53-provider"

resources:
  requests:
    memory: "64Mi"
    cpu: "20m"
  limits:
    memory: "128Mi"
    cpu: "50m"
