image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}

controllers:
  controlplane:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false


disableControllers: []
disableWebhooks: []

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

webhookConfig:
  serverPort: 443

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  machineImages:
  - name: coreos
    version: 2023.5.0
    cloudProfiles:
    - name: eu-de-1
      image: coreos-2023.5.0
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 25Gi
    backup:
      schedule: "0 */24 * * *"

gardener:
  seed:
    provider: openstack
