---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foo--bar
type: Opaque
data:
# clientID: base64(clientID)
# clientSecret: base64(clientSecret)
# subscriptionID: base64(subscriptionID)
# tenantID: base64(tenantID)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foo--bar
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keypair
  namespace: shoot--foo--bar
type: Opaque
data:
  id_rsa.pub: dGhlLXNzaC1rZXktZm9yLXRoZS1tYWNoaW5l
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# provided infrastructure status data (subnet id, etc.) is not valid/does not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foo--bar
spec:
  type: azure
  region: westeurope
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar
  infrastructureProviderStatus:
    apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    resourceGroup:
      name: my-resource-group
    networks:
      vnet:
        name: my-vnet
      subnets:
      - purpose: nodes
        name: subnet-123
    availabilitySets:
    - purpose: nodes
      id: av-nodes-1234-id
      name: av-nodes-1234-name
    routeTables:
    - purpose: nodes
      name: route-table-1
    securityGroups:
    - purpose: nodes
      name: sec-group-1
  pools:
  - name: cpu-worker
    machineType: Standard_D2_v3
    machineImage:
      name: coreos
      version: 1967.5.0
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
  # labels:
  #   key: value
  # annotations:
  #   key: value
  # taints: # See also https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # - key: foo
  #   value: bar
  #   effect: NoSchedule
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    volume:
      type: standard
      size: 35Gi
