image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
   cpu: "50m"
   memory: "64Mi"
  limits:
   cpu: "50m"
   memory: "128Mi"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

certificateConfig:
  defaultIssuer:
    name: gardener
    acme:
      email: john.doe@example.com
      server: https://acme-v02.api.letsencrypt.org/directory
    # privateKey: | # Optional key for Let's Encrypt account.
    #   -----BEGIN BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----

disableControllers: []

# imageVectorOverwrite: |
#   images:
#   - name: cert-management
#     sourceRepository: github.com/gardener/cert-management
#     repository: eu.gcr.io/gardener-project/cert-controller-manager
#     tag: "0.2.9"
