---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: garden
type: Opaque
data:
# authURL: base64(authentication-url)
# domainName: base64(domain-name)
# domainID: base64(domain-id)
# tenantName: base64(tenant-name)
# tenantID: base64(tenant-id)
# username: base64(username)
# password: base64(password)
# userDomainName: base64(user-domain-name)
# userDomainID: base64(user-domain-id)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: cloud--os--fg2d6
spec:
  type: openstack
  region: eu-west-1
  secretRef:
    name: backupprovider
    namespace: garden