---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--openstack

---
apiVersion: v1
kind: Secret
metadata:
  name: core-openstack
  namespace: shoot--foobar--openstack
type: Opaque
data:
# domainName: base64(domain-name)
# domainID: base64(domain-id)
# tenantName: base64(tenant-name)
# tenantID: base64(tenant-id)
# username: base64(username)
# password: base64(password)
# userDomainName: base64(user-domain-name)
# userDomainID: base64(user-domain-id)

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--openstack
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
    spec:
      openstack:
        keystoneURL: https://localhost
        # dnsServers:
        # - 1.1.1.1
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    status:
      lastOperation:
        state: Succeeded

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  name: infrastructure
  namespace: shoot--foobar--openstack
spec:
  type: openstack
  region: eu-de-1
  secretRef:
    name: core-openstack
    namespace: shoot--foobar--openstack
  providerConfig:
    apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    floatingPoolName: MY-FLOATING-POOL
    networks:
    # router:
    #   id: 1234
      worker: 10.250.0.0/19
    zones:
    - name: zone_1_1
  sshPublicKey: AAAA
