{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: typha-cpva
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["patch"]
{{- end }}
