{{- if .Values.config.typha.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: typha-cpva
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typha-cpva
subjects:
  - kind: ServiceAccount
    name: typha-cpva
    namespace: kube-system
{{- end }}
