apiVersion: v1
kind: Service
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: cloud-controller-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ include "cloud-controller-manager.port" . }}
    protocol: TCP
  selector:
    app: kubernetes
    role: cloud-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: kubernetes
    role: cloud-controller-manager
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: cloud-controller-manager
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        garden.sapcloud.io/role: controlplane
        app: kubernetes
        role: cloud-controller-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/from-prometheus: allowed
    spec:
      tolerations:
      - effect: NoExecute
        operator: Exists
      containers:
      - name: gcp-cloud-controller-manager
        image: {{ index .Values.images "cloud-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        {{- if semverCompare "< 1.17" .Values.kubernetesVersion }}
        - /hyperkube
        - cloud-controller-manager
        {{- else }}
        - /gcp-cloud-controller-manager
        {{- end }}
        - --allocate-node-cidrs=true
        - --cloud-provider=gce
        - --cloud-config=/etc/kubernetes/cloudprovider/cloudprovider.conf
        - --cluster-cidr={{ .Values.podNetwork }}
        - --cluster-name={{ .Values.clusterName }}
        - --concurrent-service-syncs=10
        - --configure-cloud-routes=false
        {{- include "cloud-controller-manager.featureGates" . | trimSuffix "," | indent 8 }}
        - --kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        - --leader-elect=true
        {{- if semverCompare ">= 1.13" .Values.kubernetesVersion }}
        - --secure-port={{ include "cloud-controller-manager.port" . }}
        - --port=0
        {{- end }}
        {{- if semverCompare ">= 1.12" .Values.kubernetesVersion }}
        - --authentication-kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        - --authorization-kubeconfig=/var/lib/cloud-controller-manager/kubeconfig
        - --tls-cert-file=/var/lib/cloud-controller-manager-server/cloud-controller-manager-server.crt
        - --tls-private-key-file=/var/lib/cloud-controller-manager-server/cloud-controller-manager-server.key
        {{- end }}
        - --tls-cipher-suites={{ include "kubernetes.tlsCipherSuites" . | replace "\n" "," | trimPrefix "," }}
        - --use-service-account-credentials
        - --v=2
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /srv/cloudprovider/serviceaccount.json
        livenessProbe:
          httpGet:
            path: /healthz
            {{- if semverCompare ">= 1.13" .Values.kubernetesVersion }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
            port: {{ include "cloud-controller-manager.port" . }}
          successThreshold: 1
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        ports:
        - containerPort: {{ include "cloud-controller-manager.port" . }}
          name: metrics
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: cloud-controller-manager
          mountPath: /var/lib/cloud-controller-manager
        - name: cloud-controller-manager-server
          mountPath: /var/lib/cloud-controller-manager-server
        - name: cloud-provider-config
          mountPath: /etc/kubernetes/cloudprovider
        - name: cloudprovider
          mountPath: /srv/cloudprovider
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloud-controller-manager
        secret:
          secretName: cloud-controller-manager
      - name: cloud-controller-manager-server
        secret:
          secretName: cloud-controller-manager-server
      - name: cloud-provider-config
        configMap:
          name: cloud-provider-config
      - name: cloudprovider
        secret:
          secretName: cloudprovider
