image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
   cpu: "50m"
   memory: "64Mi"
  limits:
   cpu: "50m"
   memory: "128Mi"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

certificateConfig:
  lifecycleSync: 1h
  serviceSync: 1h
  resourceNamespace: garden
  issuerName: lets-encrypt
  acme:
    email: john.doe@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # privateKey: | # Optional key for Let's Encrypt account.
    #   -----BEGIN BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----
  providers:
    clouddns:
    - name: clouddns-prod
      domains:
      - example.io
      project: project_id
      serviceAccount: | #service-account.json
        {
        "type": "service_account",
        "project_id": "demo-project"
        }
    route53:
    - name: route53-prod
      domains:
      - example.org
      region: us-east-1
      accessKeyID: your-accessKeyID
      secretAccessKey: your-secretAccessKey

disableControllers: []
