images:
- name: cert-manager
  sourceRepository: github.com/jetstack/cert-manager
  repository: quay.io/jetstack/cert-manager-controller
  tag: "v0.6.0"
- name: cert-broker
  sourceRepository: github.com/gardener/cert-broker
  repository: eu.gcr.io/gardener-project/gardener/cert-broker
  tag: "0.2.0"
