---
apiVersion: v1
kind: Namespace
metadata:
 name: garden

---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: gardener-resource-manager
 namespace: garden
 labels:
  app: gardener-resource-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: gardener-resource-manager
 labels:
  app: gardener-resource-manager
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: gardener-resource-manager
 labels:
  app: gardener-resource-manager
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: gardener-resource-manager
subjects:
- kind: ServiceAccount
  name: gardener-resource-manager
  namespace: garden

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-resource-manager
  namespace: garden
  labels:
    app: gardener-resource-manager
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: gardener-resource-manager
  template:
    metadata:
      labels:
        app: gardener-resource-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-seed-apiserver: allowed
    spec:
      tolerations:
      - effect: NoExecute
        operator: Exists
      serviceAccountName: gardener-resource-manager
      containers:
      - name: gardener-resource-manager
        image: eu.gcr.io/gardener-project/gardener/gardener-resource-manager:0.4.0
        imagePullPolicy: IfNotPresent
        command:
        - /gardener-resource-manager
        - --leader-election=true
        - --leader-election-namespace=garden
        - --resource-class=seed
        - --max-concurrent-workers=1
        - --sync-period=1m
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 23m
            memory: "49566436" 


