---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:shoot-dns-service:shoot-services
rules:
- apiGroups:
  - dns.gardener.cloud
  resources:
  - dnsentries
  - dnsentries/status
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
