---
apiVersion: v1
kind: Namespace
metadata:
  name: extension-shoot-dns-service-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:shoot-dns-service
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - extensions
  - extensions/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - "dns.gardener.cloud"
  resources:
  - "dnsentries"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "secrets"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extensions.gardener.cloud:shoot-dns-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extensions.gardener.cloud:shoot-dns-service
subjects:
- kind: ServiceAccount
  name: gardener-extension-shoot-dns-service
  namespace: extension-shoot-dns-service-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:{{ .Values.serviceName }}:shoot-services
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - dns.gardener.cloud
  resources:
  - dnsentries
  - dnsentries/status
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: extension-shoot-dns-service
  namespace: extension-shoot-dns-service-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-shoot-dns-service
  namespace: extension-shoot-dns-service-test
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-shoot-dns-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gardener-extension-shoot-dns-service
    spec:
      serviceAccountName: extension-shoot-dns-service
      containers:
      - name: gardener-extension-shoot-dns-service
        image: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper:latest
        imagePullPolicy: Always
        command:
        - /gardener-extension-hyper
        - shoot-dns-service-extension-controller-manager
        - --max-concurrent-reconciles=1
        - --ignore-operation-annotation=true
        - --garden-id=4711
        - --seed-id=0815
        - --dns-class=garden
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
